// <auto-generated />
using EF_Vb.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_Vb.Models.Migrations
{
    [DbContext(typeof(LoginSqlServerContext))]
    partial class LoginSqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EF_Vb.Models.Groep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groepen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Default",
                            Opmerkingen = ""
                        });
                });

            modelBuilder.Entity("EF_Vb.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("LoginNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paswoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("GroepLogin", b =>
                {
                    b.Property<int>("LedenId")
                        .HasColumnType("int");

                    b.Property<int>("LidVanId")
                        .HasColumnType("int");

                    b.HasKey("LedenId", "LidVanId");

                    b.HasIndex("LidVanId");

                    b.ToTable("GroepLogin");
                });

            modelBuilder.Entity("GroepLogin", b =>
                {
                    b.HasOne("EF_Vb.Models.Login", null)
                        .WithMany()
                        .HasForeignKey("LedenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Vb.Models.Groep", null)
                        .WithMany()
                        .HasForeignKey("LidVanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
