// <auto-generated />
using System;
using Boek.Data.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Boek.Data.Migrations
{
    [DbContext(typeof(BoekDb))]
    [Migration("20201201211849_versie-1")]
    partial class versie1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Boek.Data.Models.Auteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achtergrond")
                        .HasColumnType("TEXT");

                    b.Property<string>("Achternaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Afbeelding")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtiestenNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FotoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Voornaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("Boek.Data.Models.Boekje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Afbeelding")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AuteurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EAN")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN10")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN13")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("KorteInhoud")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaalKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UitgeverijId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VormId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("FotoId");

                    b.HasIndex("GenreId");

                    b.HasIndex("TaalKey");

                    b.HasIndex("UitgeverijId");

                    b.HasIndex("VormId");

                    b.ToTable("Boeken");
                });

            modelBuilder.Entity("Boek.Data.Models.DbImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DbImages");
                });

            modelBuilder.Entity("Boek.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Doelgroep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Boek.Data.Models.SubGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Doelgroep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinLeeftijd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("SubGenres");
                });

            modelBuilder.Entity("Boek.Data.Models.Taal", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Talen");
                });

            modelBuilder.Entity("Boek.Data.Models.Uitgeverij", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hoofdkwartier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Oprichter")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uitgeverijen");
                });

            modelBuilder.Entity("Boek.Data.Models.Vorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Digitaal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BoekVorm");
                });

            modelBuilder.Entity("Boek.Data.Models.Auteur", b =>
                {
                    b.HasOne("Boek.Data.Models.DbImage", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("Boek.Data.Models.Boekje", b =>
                {
                    b.HasOne("Boek.Data.Models.Auteur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId");

                    b.HasOne("Boek.Data.Models.DbImage", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId");

                    b.HasOne("Boek.Data.Models.SubGenre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("Boek.Data.Models.Taal", "Taal")
                        .WithMany()
                        .HasForeignKey("TaalKey");

                    b.HasOne("Boek.Data.Models.Uitgeverij", "Uitgeverij")
                        .WithMany()
                        .HasForeignKey("UitgeverijId");

                    b.HasOne("Boek.Data.Models.Vorm", "Vorm")
                        .WithMany()
                        .HasForeignKey("VormId");

                    b.Navigation("Auteur");

                    b.Navigation("Foto");

                    b.Navigation("Genre");

                    b.Navigation("Taal");

                    b.Navigation("Uitgeverij");

                    b.Navigation("Vorm");
                });

            modelBuilder.Entity("Boek.Data.Models.SubGenre", b =>
                {
                    b.HasOne("Boek.Data.Models.Genre", "Genre")
                        .WithMany("SubGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Boek.Data.Models.Genre", b =>
                {
                    b.Navigation("SubGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
