// <auto-generated />
using EF_Vb.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_Vb.Models.Migrations.LoginSqlLite
{
    [DbContext(typeof(LoginSqlLiteContext))]
    partial class LoginSqlLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EF_Vb.Models.Groep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groepen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Default",
                            Opmerkingen = ""
                        });
                });

            modelBuilder.Entity("EF_Vb.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Paswoord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("GroepLogin", b =>
                {
                    b.Property<int>("LedenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LidVanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LedenId", "LidVanId");

                    b.HasIndex("LidVanId");

                    b.ToTable("GroepLogin");
                });

            modelBuilder.Entity("GroepLogin", b =>
                {
                    b.HasOne("EF_Vb.Models.Login", null)
                        .WithMany()
                        .HasForeignKey("LedenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Vb.Models.Groep", null)
                        .WithMany()
                        .HasForeignKey("LidVanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
